name: Archlinux make

on:
  push:
    branches: [ master, development, build-automation, digital-stage-client ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: submods
      run: git submodule init && git submodule update && (cd libov && git submodule update --init)
    - name: tascar
      run: wget -qO- https://apt.hoertech.de/openmha-packaging.pub | sudo apt-key add - &&
           sudo apt-add-repository 'deb http://apt.hoertech.de/ bionic universe'
    - name: dependencies
      run: sudo apt update &&
           sudo apt install --assume-yes git docker
    - name: buildenv
      run: docker build -t archlinux docker/archlinux/
    - name: make
      run: docker run --rm archlinux
