name: Archlinux make

on:
  push:
    branches: [ master, development, build-automation, digital-stage-client ]

jobs:
  build:

    runs:
      using: docker
      image: archlinux docker/archlinux/Dockerfile
    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
