name: Archlinux make

on:
  push:
    branches: [ master, development, build-automation, digital-stage-client ]

jobs:
  build:

    runs:
      using: docker
      image: archlinux docker/archlinux/Dockerfile
