name: MacOS make

on:
  push:
    branches: [ development, digital-stage-client ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: dependencies
      run: brew install pkgconfig libxml2 glibmm libxml++ jack liblo libsndfile gtkmm3 eigen boost gsl fftw libsamplerate cpprestsdk nlohmann-json openssl
    - name: make
      run: ./build_osx.sh
    - name: packlibs
      run: ./make_portable
    - uses: actions/upload-artifact@v2
      with:
        name: osx-build
        path: build/*
