name: Ubuntu make

on:
  push:
    branches: [ master, development, build-automation, digital-stage-client ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: submods
      run: git submodule init && git submodule update && (cd libov && git submodule update --init)
    - name: tascar
      run: wget -qO- https://apt.hoertech.de/openmha-packaging.pub | sudo apt-key add - &&
           sudo apt-add-repository 'deb http://apt.hoertech.de/ bionic universe'
    - name: dependencies
      run: sudo apt update &&
           sudo apt install --assume-yes git zita-njbridge liblo-dev nodejs libcurl4-openssl-dev build-essential libasound2-dev libeigen3-dev libfftw3-dev libfftw3-double3 libfftw3-single3 libgsl-dev libjack-jackd2-dev libltc-dev libmatio-dev libsndfile1-dev libsamplerate0-dev mhamakedeb libboost-all-dev libxml++2.6-dev libcpprest-dev nlohmann-json-dev
    - name: make
      run: make
    - name: packaging
      run: make packaging
    - uses: actions/upload-artifact@v2
      with:
        name: debian
        path: packaging/deb/debian/*/*.deb
